import { CandidateProfile, Workspace, WorkspaceSchema, makeId, nowIso } from "./domain";

function candidateTemplate(): CandidateProfile {
  return {
    id: makeId("candidate"),
    fullName: "Maya Chen",
    headline: "Frontend engineer building fast, accessible product experiences",
    email: "maya.chen@example.test",
    phone: "+1 415 555 0138",
    location: "San Francisco, CA",
    website: "",
    githubUrl: "",
    portfolioUrl: "",
    summary: "",
    skills: ["TypeScript", "React", "Next.js", "Accessibility", "Testing"],
    education: ["B.S. Computer Science · University of Washington · 2024"],
    experience: [
      {
        id: makeId("experience"),
        company: "Northstar Labs",
        title: "Frontend Engineer Intern",
        location: "Remote",
        startDate: "Jun 2023",
        endDate: "Sep 2023",
        bullets: ["", ""],
      },
    ],
    projects: [
      {
        id: makeId("project"),
        name: "Atlas study planner",
        url: "",
        description: "",
        technologies: ["React", "TypeScript"],
      },
    ],
    certifications: [],
    updatedAt: nowIso(),
  };
}

export function createWorkspace(mode: "blank" | "demo" = "blank"): Workspace {
  const now = nowIso();
  const syntheticSources = mode === "demo" ? [
    {
      id: makeId("source"),
      kind: "resume" as const,
      label: "Synthetic resume fixture",
      fileName: "synthetic-resume.md",
      excerpt: "Maya Chen builds accessible TypeScript and React interfaces, writes tests, and improves product workflows for early-career users.",
      extractionStatus: "ready" as const,
      status: "ready" as const,
      createdAt: now,
    },
    {
      id: makeId("source"),
      kind: "portfolio" as const,
      label: "Synthetic project notes",
      fileName: "synthetic-project-notes.txt",
      excerpt: "Atlas is a React and TypeScript study planner. Maya designed the information architecture, implemented keyboard navigation, and documented the testing approach.",
      extractionStatus: "ready" as const,
      status: "ready" as const,
      createdAt: now,
    },
    {
      id: makeId("source"),
      kind: "linkedin-screenshot" as const,
      label: "Synthetic LinkedIn screenshot",
      fileName: "synthetic-linkedin-screenshot.svg",
      excerpt: "Synthetic profile card: Maya Chen shares an accessibility testing lesson from the Atlas study planner. This image is a fixture, not a real profile.",
      extractionStatus: "ready" as const,
      status: "ready" as const,
      createdAt: now,
    },
    {
      id: makeId("source"),
      kind: "job" as const,
      label: "Synthetic target role brief",
      fileName: "synthetic-target-job.txt",
      excerpt: "Northstar Labs is looking for a product-minded frontend engineer intern who can work with React and TypeScript, build accessible interfaces, collaborate with designers, and write reliable tests.",
      extractionStatus: "ready" as const,
      status: "ready" as const,
      createdAt: now,
    },
  ] : [];
  const syntheticJobId = mode === "demo" ? makeId("job") : undefined;
  const workspace: Workspace = {
    schemaVersion: 1,
    id: makeId("workspace"),
    name: mode === "demo" ? "Maya’s live demo workspace" : "Untitled career workspace",
    mode,
    stage: "candidate",
    candidate: mode === "demo" ? candidateTemplate() : {
      id: makeId("candidate"),
      fullName: "",
      headline: "",
      email: "",
      phone: "",
      location: "",
      website: "",
      githubUrl: "",
      portfolioUrl: "",
      summary: "",
      skills: [],
      education: [],
      experience: [],
      projects: [],
      certifications: [],
      updatedAt: now,
    },
    sources: syntheticSources,
    claims: [],
    companies: [],
    jobs: mode === "demo" && syntheticJobId ? [{
      id: syntheticJobId,
      title: "Product-minded frontend engineer intern",
      companyName: "Northstar Labs",
      url: "https://example.test/jobs/product-minded-frontend-intern",
      location: "Remote",
      employmentType: "Internship",
      description: syntheticSources.find((source) => source.kind === "job")?.excerpt || "",
      requirements: [],
      sourceIds: syntheticSources.filter((source) => source.kind === "job").map((source) => source.id),
      status: "needs-analysis" as const,
      discoveredAt: now,
    }] : [],
    matchReports: [],
    resumes: [],
    agentRuns: [],
    activeJobId: syntheticJobId,
    privacyDisclosure: {
      version: 1,
      shown: false,
      accepted: false,
      fieldsSent: ["name", "headline", "summary", "skills", "experience", "education", "projects", "certifications"],
      sourceIds: syntheticSources.map((source) => source.id),
      filesAnalyzed: syntheticSources.filter((source) => source.fileName).map((source) => source.fileName!),
      urlsFetched: [],
      provider: "OpenCode Zen",
      textModel: "opencode/deepseek-v4-flash-free",
      imageModel: "opencode/mimo-v2.5-free",
      redactionNote: "Contact details, API keys, raw file contents, and local paths are excluded from model context and logs.",
      localStorageNote: "Workspace JSON, attachments, exports, and redacted run events stay in the configured local data directory.",
    },
    createdAt: now,
    updatedAt: now,
  };
  return WorkspaceSchema.parse(workspace);
}
